#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Запускаем тесты
npm run test
if [ $? -ne 0 ]; then
  echo "Tests failed, aborting commit"
  exit 1
fi

# Запускаем линтинг
npm run lint
if [ $? -ne 0 ]; then
  echo "Linting failed, aborting commit"
  exit 1
fi
